In [3]:
import numpy as np 

# Array Numpy (lista otimizada)

In [3]:
numeros = [2,4,8,16,32,64,128]

array_numeros = np.array(numeros)

array_numeros 

array([  2,   4,   8,  16,  32,  64, 128])

* Operações Vetorizadas

In [25]:
array_numeros *3 /2 
#outra forma -> VS code precisa colocar o print, exemplo =  print(array_numeros +4)




array([  3.,   6.,  12.,  24.,  48.,  96., 192.])

<b> Comparações Vetorizadas <b>

In [49]:
array_aleatorios = np.array ([7,17,11,10,20,35]) #-> nao precisa criar um lsita, ja cria dentro do array 

print (array_aleatorios %2 == 0)

[False False False  True  True False]


<b> Filtro condicional <b>

In [50]:

#print(array_aleatorios [array_aleatorios % 2 ==0])
#print(array_aleatorios [array_aleatorios % 2 == 1])

print("Maiores que 20:", array_aleatorios[array_aleatorios > 20]) #Mostra numeros maior que vinte
print("Pares:",array_aleatorios[array_aleatorios % 2 == 0 ]) #Mostra apenas os valores pares
print("Impares:",array_aleatorios[array_aleatorios % 1  ==0]) #Mostra apenas os valores ímpares


Maiores que 20: [35]
Pares: [10 20]
Impares: [ 7 17 11 10 20 35]


In [50]:

#print(array_aleatorios [array_aleatorios % 2 ==0])
#print(array_aleatorios [array_aleatorios % 2 == 1])

print("Maiores que 20:", array_aleatorios[array_aleatorios > 20]) #Mostra numeros maior que vinte
print("Pares:",array_aleatorios[array_aleatorios % 2 == 0 ]) #Mostra apenas os valores pares
print("Impares:",array_aleatorios[array_aleatorios % 1  ==0]) #Mostra apenas os valores ímpares


Maiores que 20: [35]
Pares: [10 20]
Impares: [ 7 17 11 10 20 35]


<b> Acessando Elementos <b>

In [39]:
print(array_aleatorios[0])
print(array_aleatorios[0:2])


7
[ 7 17]


# Operações com Arrays

In [53]:
print(array_aleatorios)
print("Soma",np.sum(array_aleatorios))
print("Média",np.mean(array_aleatorios))
print("Mínimo",np.min(array_aleatorios))
print("Máximo",np.max(array_aleatorios))

[ 7 17 11 10 20 35]
Soma 100
Média 16.666666666666668
Mínimo 7
Máximo 35


# LISTA DE EXERCICIOS

In [5]:
array_numeros = np.array([1,2,3,4,5]) #exercicio 2 

print(array_numeros *2 +10 **2)

[102 104 106 108 110]


<b>  média, máximo e mínimo <b>

In [6]:
array_numeros = np.array([[7.5, 8.0, 6.5, 9.0, 5.5]]) #exercicio 3
print("Média",np.mean(array_numeros))
print("Máximo",np.max(array_numeros))
print("Mínimo",np.min(array_numeros))

Média 7.3
Máximo 9.0
Mínimo 5.5


<b> Normalize o array <b>

In [7]:
array_divisao = np.array([10,20,30,40,50]) #exercicio 4
print(array_divisao / np.max(array_divisao))


[0.2 0.4 0.6 0.8 1. ]


<b> filtre apenas maiores de idade <b>

In [8]:
array_idades = np.array ( [15,18,22,17,30,16]) #exercicio 5
print("Maiores de idade:", array_idades[array_idades > 18])
 


Maiores de idade: [22 30]


<b> Filtre valores maiores que 10 e menores que 25 no array <b>

In [9]:
array_valores = np.array ([5,10,15,20,25,30]) #exercicio 6
print(array_valores [ (array_valores > 10) & (array_valores < 25)])

[15 20]


<b> Conte quantos valores são maiores ou iguais a 6 no array <b>

In [10]:
valores_igual = np.array ([4,6,7,5,8,3,9]) #exercicio 7
print(valores_igual [ (valores_igual >= 6)])

[6 7 8 9]


<b> Aumente em 500 os valores menores que 2000 no array <b>

In [67]:
aumento = np.array ([1000,2000,3000,1500]) #exercicio 8

aumento [ (aumento < 2000 )] += 500

aumento


array([1500, 2000, 3000, 2000])

<b> aumento de preços <b>

In [24]:
valores = np.array ([10,20,30,40]) #exercicio 9
valores = valores * 1.1
print(valores)

[11. 22. 33. 44.]


<b> - Filtro e Média <b>

In [114]:
preços = np.array ( [10,20,30,40,50]) #exercicio 10
preços_filtrados = preços[preços > 25] 
print("preços_filtrados", preços_filtrados)
print("Média",np.mean(preços_filtrados))

preços_filtrados [30 40 50]
Média 40.0


<b> Relacionamento entre Arrays <b>

In [65]:
idade = np.array ([18, 25, 30, 22, 40]) #exercicio 11
salario = np.array ( [2000, 3000, 4000, 2500, 5000])
print( "salario das pessoas com idade > 25",  salario [idade > 25])
print("Médias dos salarios", np.mean(salario [idade > 25]))

salario das pessoas com idade > 25 [4000 5000]
Médias dos salarios 4500.0


<b> - Índices Condicionais <b>

In [113]:
valores_igual = np.array ([5, 7, 8, 4, 9]) #exercicio 12
print(valores_igual [ (valores_igual >= 7)])

np.where(valores_igual>=7)

[7 8 9]


(array([1, 2, 4]),)

<b>Números Pares <b>

In [61]:
pares = np.array ([1,2,3,4,5,6,7,8,9,10]) #exercicio 13
print("Numeros Pares:",pares[pares % 2 == 0 ])

Numeros Pares: [ 2  4  6  8 10]


<b> - Valores Acima da Média <b>

In [14]:
import numpy as np

aleatorio = [np.random.randint (0,100) for x in range(10)] #exercicio 14
aleatorio = np.array(aleatorio)
media = np.mean(aleatorio)
print("Média",media)
print("Valores maiores:",aleatorio[aleatorio > media])

Média 48.5
Valores maiores: [63 52 76 77 49 75 63]


<b> Análise de Notas <b>

In [17]:
notas = np.array ([5, 7, 8, 6, 4, 9, 10]) #exercicio 15
media = np.mean(notas)
print(notas)
print("Média",media)
print("Valores maiores que a média:", notas[notas > media])
print(len(notas [notas > media])) #numeros acima da média geral
#sum (notas > media)

[ 5  7  8  6  4  9 10]
Média 7.0
Valores maiores que a média: [ 8  9 10]
3
